
CREATE TABLE TBL_TABLA(
	TABLAID			NUMBER(10,0)	NOT NULL,
	TABLANAME		VARCHAR2(64)	NOT NULL
);

CREATE TABLE TBL_CATALOGO(
	TABLAID			NUMBER(10,0)	NOT NULL,
	CATALOGOID		NUMBER(10,0)	NOT NULL,
	CODIGO			VARCHAR(10)		NOT NULL,
	VALOR			VARCHAR2(512)	NOT NULL
);

CREATE TABLE TBL_USER(
	USERID			NUMBER(10,0)	NOT NULL,
	USERNAME		VARCHAR2(128)	NOT NULL,
	USERLAST_NAME	VARCHAR2(200)	NOT NULL,
	USERLOGIN		VARCHAR2(32)	NOT NULL,
	USERPASSWORD	VARCHAR2(200)	NOT NULL,
	USERCREATION	DATE			NOT NULL,
	USEREMAIL		VARCHAR2(64)	NOT NULL,
	USERESTADO		CHAR(1)			NOT NULL
);

CREATE TABLE TBL_ADDRESS(
	ADDRESSID		NUMBER(10,0)	NOT NULL,
	USERID			NUMBER(10,0)	NOT NULL,
	ADDRESS			VARCHAR2(256)	NOT NULL,
	ADDRESSTYPE		CHAR(1)			NOT NULL,
	ADDRESSMAIN		NUMBER(1,0)		NOT NULL
);

ALTER TABLE TBL_TABLA ADD CONSTRAINT TBL_TABLA_PK01 PRIMARY KEY(TABLAID);
ALTER TABLE TBL_CATALOGO ADD CONSTRAINT TBL_CATALOGO_PK01 PRIMARY KEY(TABLAID, CATALOGOID);
ALTER TABLE TBL_USER ADD CONSTRAINT TBL_USER_PK01 PRIMARY KEY(USERID);
ALTER TABLE TBL_ADDRESS ADD CONSTRAINT TBL_ADDRESS_PK01 PRIMARY KEY(ADDRESSID, USERID);

ALTER TABLE TBL_CATALOGO ADD CONSTRAINT TBL_CATALOGO_FK01 FOREIGN KEY(TABLAID) REFERENCES TBL_TABLA(TABLAID);
ALTER TABLE TBL_ADDRESS ADD CONSTRAINT TBL_ADDRESS_FK01 FOREIGN KEY(USERID) REFERENCES TBL_USER(USERID);